-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 23:55:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema school_timetable
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school_timetable` ;

-- -----------------------------------------------------
-- Schema school_timetable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school_timetable` ;
USE `school_timetable` ;

-- -----------------------------------------------------
-- Table `school_timetable`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`subjects` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`subjects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`teachers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`teachers` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`teachers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject_id` BIGINT UNSIGNED NOT NULL,
  `full_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_teachers_subjects1_idx` (`subject_id` ASC),
  CONSTRAINT `fk_teachers_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `school_timetable`.`subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`class_names`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`class_names` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`class_names` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`school_timetables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`school_timetables` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`school_timetables` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hashcode` DECIMAL(10,0) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`class_timetables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`class_timetables` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`class_timetables` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `class_id` BIGINT UNSIGNED NULL,
  `school_timetable_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_class1_idx` (`class_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_class_timetable_school_timetables1_idx` (`school_timetable_id` ASC),
  CONSTRAINT `fk_schedule_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `school_timetable`.`class_names` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_timetable_school_timetables1`
    FOREIGN KEY (`school_timetable_id`)
    REFERENCES `school_timetable`.`school_timetables` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`day_names`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`day_names` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`day_names` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`days` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`days` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timetable_id` BIGINT UNSIGNED NULL,
  `day_name_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_day_schedule1_idx` (`timetable_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_days_day_names1_idx` (`day_name_id` ASC),
  CONSTRAINT `fk_day_schedule1`
    FOREIGN KEY (`timetable_id`)
    REFERENCES `school_timetable`.`class_timetables` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_days_day_names1`
    FOREIGN KEY (`day_name_id`)
    REFERENCES `school_timetable`.`day_names` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school_timetable`.`lessons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school_timetable`.`lessons` ;

CREATE TABLE IF NOT EXISTS `school_timetable`.`lessons` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `teacher_id` BIGINT UNSIGNED NOT NULL,
  `day_id` BIGINT UNSIGNED NULL,
  `lesson_number` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lesson_day1_idx` (`day_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_lessons_teachers1_idx` (`teacher_id` ASC),
  CONSTRAINT `fk_lesson_day1`
    FOREIGN KEY (`day_id`)
    REFERENCES `school_timetable`.`days` (`id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_teachers1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school_timetable`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
